[package]
name = "btc-data-light-server"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"
description = "Silent Payment light-data archive indexer and SQLite-backed HTTP server."

[lib]
name = "btc_data_light_server"
path = "src/lib.rs"

[[bin]]
name = "light-indexer"
path = "src/bin/light_indexer.rs"

[[bin]]
name = "light-server"
path = "src/bin/light_server.rs"

[dependencies]
axum = "0.8.9"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite", "macros", "migrate"] }
anyhow.workspace = true
capnp.workspace = true
clap.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
async-trait.workspace = true
btc-data-sources.workspace = true
btc-data-core.workspace = true
bitcoin.workspace = true
sha2.workspace =  true
futures.workspace = true
rocksdb = "0.24.0"
[build-dependencies]
capnpc.workspace = true

[features]
default = ["btc-data-sources/ipc"]